services:
    redis-platform:
        container_name: redis-queue-platform
        image: redis
        ports:
            - 6380:6379
        volumes:
            - redis:/data
volumes:
    redis:
        driver: local
