services:
    redis:
        container_name: redis-queue
        image: redis
        ports:
            - 6379:6379
        volumes:
            - redis:/data

volumes:
    redis:
        driver: local
